#!/usr/bin/env bash
# Idempotent installer for the OPSEC hooks.
#
# Filesystem note: this repo is typically accessed via an sshfs mount
# (rog:/home/jcviau/voxyflow → /home/jcviau/voxyflow-rog locally). sshfs
# accepts `ln -s` but creates symlinks whose targets are resolved on the
# REMOTE side, so a link target like `$REPO_ROOT/scripts/...` ends up broken
# from the local view (and may also EPERM on subsequent overwrite). We
# therefore default to writing a tiny shim that invokes the canonical
# scripts/opsec-check.sh via its absolute path — works regardless of whether
# the hook ends up on the sshfs mount or a native filesystem. Pass
# VOXYFLOW_OPSEC_USE_SYMLINK=1 to opt back into symlink installation on a
# native filesystem if you prefer it.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
SCRIPTS_DIR="$REPO_ROOT/scripts"

write_shim() {
  local mode="$1"      # --staged or --file
  local dst="$2"
  cat > "$dst" <<SHIM
#!/usr/bin/env bash
# Auto-generated by scripts/install-opsec-hooks.sh — do not edit.
exec "$SCRIPTS_DIR/opsec-check.sh" $mode "\$@"
SHIM
  chmod +x "$dst"
}

install_one() {
  local hook_name="$1"   # pre-commit or commit-msg
  local src="$2"         # scripts/pre-commit-opsec.sh (used only for symlink path)
  local mode="$3"        # --staged or --file
  local dst="$HOOKS_DIR/$hook_name"

  if [[ -e "$dst" || -L "$dst" ]]; then
    if [[ "${FORCE:-0}" != "1" ]]; then
      echo "⚠️  $hook_name already installed (use FORCE=1 to overwrite). Skipping." >&2
      return 0
    fi
  fi

  # Always clear any existing entry (file, broken symlink, etc.).
  rm -f "$dst" 2>/dev/null || true

  if [[ "${VOXYFLOW_OPSEC_USE_SYMLINK:-0}" == "1" ]]; then
    if ln -s "$src" "$dst" 2>/dev/null && [[ -e "$dst" ]]; then
      echo "✓ symlinked $hook_name → $src"
      return 0
    fi
    rm -f "$dst" 2>/dev/null || true
    echo "ℹ️  symlink rejected by filesystem, falling back to shim" >&2
  fi

  write_shim "$mode" "$dst"
  echo "✓ wrote shim $hook_name → $dst (invokes $SCRIPTS_DIR/opsec-check.sh $mode)"
}

chmod +x "$SCRIPTS_DIR/opsec-check.sh" \
        "$SCRIPTS_DIR/pre-commit-opsec.sh" \
        "$SCRIPTS_DIR/commit-msg-opsec.sh"

install_one pre-commit "$SCRIPTS_DIR/pre-commit-opsec.sh" --staged
install_one commit-msg "$SCRIPTS_DIR/commit-msg-opsec.sh" --file

echo ""
echo "Smoke test: echo 'this mentions ROG' | $SCRIPTS_DIR/opsec-check.sh --stdin"
if echo 'this mentions ROG' | "$SCRIPTS_DIR/opsec-check.sh" --stdin >/dev/null 2>&1; then
  echo "⚠️  smoke test FAILED: scanner did not catch 'ROG'"
  exit 1
else
  echo "✓ smoke test passed (scanner caught 'ROG')"
fi
